### ISSUE TITLE
Feature Suggestion - Dynamic App

### ISSUE THREAD

**Issue by sampathbalivada** [iampawan/GDG-DevFest-App#2]
The current implementation requires us to build and upload the app for each and every DevFest. Making it dynamic can make the experience for organisers better. I think we should be able to do this using Google Sheets and local storage (sqflite).

Please comment on this so that I can prepare a draft implementation for the same.

**Comment by iampawan** [comment]
The idea is that only but it's gonna take some time because it can be only done phase by phase. I am looking to collect more information about their ways to gather the data. Next target as of now for me is to make it compatible with firebase and provide some kind of admin panel to them. Let me know if you have more suggestions like this. Thanks

**Comment by sampathbalivada** [comment]
That sounds awesome. Additionally, we can collect data using Google sheets and try to run a Cloud Function to extract data and store in Firebase or probably create an extension to the app or a separate app with additional privileges for organisers to modify data.

**Comment by iampawan** [comment]
For that, I am gonna make an admin panel soon. But I guess it is going to take some time.
